name: Validation

on:
  push:
  pull_request:

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  export:
    name: Export Pipeline Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout osm2vdv462
        uses: actions/checkout@v3

      - name: Run export pipeline with example data
        run: ./export.sh ./example_data/tu-campus_technopark.osm.pbf

      - name: Upload export as artifact
        uses: actions/upload-artifact@v3
        with:
          name: example_export
          path: export.xml

  validate:
    name: NeTEx Schema Validation
    runs-on: ubuntu-latest
    needs: export
    steps:
      - name: Checkout NeTEx XSD
        uses: actions/checkout@v3
        with:
          repository: NeTEx-CEN/NeTEx

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Download example export
        uses: actions/download-artifact@v3
        with:
          name: example_export

      - name: Validate example export against NeTEx XSD
        run: xmllint --noout --schema xsd/NeTEx_publication.xsd exampl_export.xml
